[project]
name = "Agent-Smith"
version = "0.0.1"
description = "Code generator agent."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flake8",
    "mypy",
    "pydantic",
    "rich",
    "google-genai",
    "docker",
    "types-docker",
    "fire",
    "dotenv",
    "groq",
    "cohere",
    "openai",
    "mcp",
    "fastmcp>=3.4.2",
    "mistralai",
	  "cerebras"
]

[dependency-groups]
dev = [
    "types-requests",
    "types-setuptools",
    "types-docopt",
    "pytest>=9.1.1",
]

[project.scripts]
sandbox = "student.src.__main__:main"

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["."]
include = ["student*"]

[[tool.mypy.overrides]]
module = "fire"
ignore_missing_imports = true
